Models/ErrorViewModel.cs
using System;

namespace SqrtCalc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CalcController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace SqrtCalc.Controllers
{
    public class CalcController : Controller
    {
        // [HttpGet] by default uses a http get method
        public ActionResult Sqrt()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Sqrt(string firstNumber, string secondNumber)
        {

                try
                {
                    // ViewBag.ErrorMessageValue = "";

                    if (int.Parse(firstNumber) < 0 && int.Parse(secondNumber) < 0)
                    {
                        ViewBag.ErrorMessageValue = "Please insert a positive number!";

                    }else 
                    {
                        var num1 = double.Parse(firstNumber);
                        var num2 = double.Parse(secondNumber);
                        var firstSqrt = Math.Sqrt(num1);
                        var secondSqrt = Math.Sqrt(num2);
                        double highSqrt;

                        if (firstSqrt > secondSqrt)
                        {
                            highSqrt = firstSqrt;
                        }
                        else
                        {
                            highSqrt = secondSqrt;
                        }
                        //store values
                        ViewBag.Result = highSqrt; ViewBag.numberOneValue = num1;
                        ViewBag.numberTwoValue = num2; ViewBag.firstSqrtValue = firstSqrt;                    
                        ViewBag.secondSqrtValue = secondSqrt;
                    
                    }
                    
                }
                catch (FormatException ex)
                {
                    // Handling FormatExceptions and parsing message to User
                    var exceptionValue = ex.Message;
                    ViewBag.FormatError = "Hi Buddy, Only Numbers are accepted " + exceptionValue;
                }
                catch (ArgumentNullException ex)
                {
                    var exceptionValueNullException = ex.Message;
                    ViewBag.FormatErrorNullException = "Please Insert a Value and try again";
                }
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SqrtCalc.Models;

namespace SqrtCalc.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string firstNumber, string secondNumber)
        {
          // Check if values are numbers and if false set error
          decimal number = 0;
          bool canConvertFirst = decimal.TryParse(firstNumber, out number);
          bool canConvertSecond = decimal.TryParse(secondNumber, out number);
          if (!canConvertFirst || !canConvertSecond) 
          {
            ViewBag.Error = "not string";
            return View();
          }

          // Collect values and convert to ints
          decimal firstNum = decimal.Parse(firstNumber);
          decimal secondNum = decimal.Parse(secondNumber);
      
          // Check if values are less than zero and set error if true
          if (firstNum < 0 || secondNum < 0) 
          {
            ViewBag.Error = "negative number";
            return View();
          }

          // Get square root of both numbers
          decimal firstNumRoot = (decimal)Math.Sqrt((double)firstNum);
          decimal secondNumRoot = (decimal)Math.Sqrt((double)secondNum);

          // Check if square roots are equal and if true return error
          if (firstNumRoot == secondNumRoot)
          {
            ViewBag.Error = "equal root";
            return View();
          }

          // Else return the view with neccessary values
          if (firstNumRoot > secondNumRoot)
          {
            ViewBag.HigherNum = firstNum;
            ViewBag.HigherRoot = Math.Round((double)firstNumRoot, 2);
            ViewBag.LowerNum = secondNum;
            ViewBag.LowerRoot = Math.Round((double)secondNumRoot, 2);
            return View();
          }
          else 
          {
            ViewBag.HigherNum = secondNum;
            ViewBag.HigherRoot = Math.Round((double)secondNumRoot, 2);
            ViewBag.LowerNum = firstNum;
            ViewBag.LowerRoot = Math.Round((double)firstNumRoot, 2);
            return View();
          }
          
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calc/Sqrt.cshtml
@{
    ViewData["Title"] = "Find a Squaredroot Number";
}

<div class="text-center">
    <h1 class="display-4">Find the highest number square root:</h1>
</div>


<div class="jumbotron text-center">

    <form asp-controller="Calc" asp-action="Sqrt" method="POST">
        <input type="text" name="firstNumber" placeholder="First Number" autocomplete="OFF" />
        <input type="text" name="secondNumber" placeholder="Second Number" autocomplete="OFF" />

        <button type="submit">Calc</button>
    </form>

</div>


@{
    if (ViewBag.ErrorMessageValue != null)
    {
        <div class="text-center text-danger mt-2">
            <h2>@ViewBag.ErrorMessageValue</h2>
        </div>
    }
}

@{
    if (ViewBag.FormatError != null)
    {
        <div class="text-center text-danger mt-2">
            <h2>@ViewBag.FormatError</h2>
        </div>
    }
}

@{
    if (ViewBag.Result != null)
    {
        
        <div class="modal modal-open text-center text-success mt-2">
            @{
                if (ViewBag.firstSqrtValue > ViewBag.secondSqrtValue)
                {
                    <h2>The number @ViewBag.numberOneValue with Square root @ViewBag.firstSqrtValue has a higher square root than the number @ViewBag.numberTwoValue with square root @ViewBag.secondSqrtValue</h2>
                }
                else if (ViewBag.secondSqrtValue > ViewBag.firstSqrtValue)
                {
                    <h2>The number @ViewBag.numberTwoValue with Square root @ViewBag.secondSqrtValue has a higher square root than the number @ViewBag.numberOneValue with square root @ViewBag.firstSqrtValue</h2>
                }
                else if (ViewBag.secondSqrtValue == ViewBag.firstSqrtValue)
                {
                    <h2>The number @ViewBag.numberOneValue with Square root @ViewBag.firstSqrtValue has an equal square root with the number @ViewBag.numberTwoValue with square root @ViewBag.secondSqrtValue</h2>
                    <p>You may please enter another value</p>
                }
            }
            
        </div>    
    }
}

Views/Home/Compute.cshtml
@{
    ViewData["Title"] = "Find a Squaredroot Number";
}

<div class="text-center">
    <h1 class="display-6">Find the highest number square root:</h1>
</div>

<div class="jumbotron text-center">
    <form asp-controller="Calculator" asp-action="compute" method="POST">
        <input type="text" name="firstNumber" placeholder="Number 1" autocomplete="OFF" />
        <input type="text" name="secondNumber" placeholder="Number 2" autocomplete="OFF" />

        <button type="submit">Display</button>
    </form>
</div>


@{
    if (ViewBag.ErrorMessageValue != null)
    {
        <div class="text-center text-danger mt-2">
            <h2>@ViewBag.ErrorMessageValue</h2>
        </div>
    }
}

@{
    if (ViewBag.FormatError != null)
    {
        <div class="text-center text-danger mt-2">
            <h2>@ViewBag.FormatError</h2>
        </div>
    }
}

@{
    if (ViewBag.Result != null)
    {
        
        <div class="modal modal-open text-center text-success mt-2">
            @{
                if (ViewBag.firstSqrtValue > ViewBag.secondSqrtValue)
                {
                    <h2>The number @ViewBag.numberOneValue with Square root @ViewBag.firstSqrtValue has a higher square root than the number @ViewBag.numberTwoValue with square root @ViewBag.secondSqrtValue</h2>
                }
                else if (ViewBag.secondSqrtValue > ViewBag.firstSqrtValue)
                {
                    <h2>The number @ViewBag.numberTwoValue with Square root @ViewBag.secondSqrtValue has a higher square root than the number @ViewBag.numberOneValue with square root @ViewBag.firstSqrtValue</h2>
                }
                else if (ViewBag.secondSqrtValue == ViewBag.firstSqrtValue)
                {
                    <h2>The number @ViewBag.numberOneValue with Square root @ViewBag.firstSqrtValue has an equal square root with the number @ViewBag.numberTwoValue with square root @ViewBag.secondSqrtValue</h2>
                    <p>You may please enter another value</p>
                }
            }
            
        </div>    
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Square Root Calculator";
}

<header>
  <h1 class="text-center">@ViewData["Title"]</h1>
</header>
<hr>
<main style="width:450px;max-width:100%;margin:0 auto;">
  <div>
    <p>This Web Application accept Two numbers and display which has a higher square root to the user</p>
  </div>
  <div class="text-center">
    @{
      if (ViewBag.Error == "not string")
      {
        <p class="alert alert-danger" role="alert">Error: You have entered values that are not numbers. Try again</p>
      }
      if (ViewBag.Error == "negative number") 
      {
        <p class="alert alert-danger" role="alert">Error: You can't enter a negative numbers. Try again</p>
      }
      if (ViewBag.Error == "equal root")
      {
        <p class="alert alert-danger" role="alert">Error: The numbers have equal square roots. Please enter another value</p>
      }
      if (ViewBag.HigherNum != null)
      {
        <p class="alert alert-success" role="alert">
          The number @ViewBag.HigherNum with square root @ViewBag.HigherRoot has a higher square root than the number 
          @ViewBag.LowerNum with square root @ViewBag.LowerRoot
        </p>
      }

    }
  </div>
  <div class="jumbotron text-center">
    <form asp-controller="Home" asp_action="Index" method="post">
      <div class="form-group">
        <label for="first_number">Enter First Number</label>
        <input type="text" class="form-control" name="firstNumber" id="first_number" placeholder="Enter first number" required>
      </div>
      <div class="form-group">
        <label for="second_number">Enter Second Number</label>
        <input type="text" class="form-control" name="secondNumber" id="second_number" placeholder="Enter second number" required>
      </div>
      <button type="submit" class="btn btn-primary btn-block">Submit</button>
    </form>
  </div>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SqrtCalc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SqrtCalc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SqrtCalc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>